[package]
name = "throttler"
version = "0.1.0"
authors = ["gciruelos <gonzalo.ciruelos@gmail.com>"]
repository = "https://github.com/gciruelos/rust-throttler.git"

description = "Simple throttler written in Rust"
license = "Apache-2.0"

[dependencies]
